version: '2'
services:
  backend:
    container_name: todo-backend
    image: jboss/wildfly:latest
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./build/libs:/opt/jboss/wildfly/standalone/deployments/
  redis:
    container_name: redis-db
    image: redis:3
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    driver: local