/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alienmojo' at '6/15/16 5:55 PM' with Gradle 2.11
 *
 * @author alienmojo, @date 6/15/16 5:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
